/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gulshan
 */
public class AddMember extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudent
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public AddMember() {
        initComponents();
        con = (Connection) DBCon.getConnection();
        autoId();
        //clearField();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_table = new javax.swing.JTable();
        txt_mid = new javax.swing.JTextField();
        txt_mname = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        m_dob = new com.toedter.calendar.JDateChooser();
        m_gender = new javax.swing.JComboBox<>();
        txt_memail = new javax.swing.JTextField();
        txt_mcontact = new javax.swing.JTextField();
        m_type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1020, 540));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 153, 255));
        jLabel15.setText("Member");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        btn_add.setBackground(new java.awt.Color(0, 204, 204));
        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.setIconTextGap(8);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 180, 30));

        btn_update.setBackground(new java.awt.Color(0, 204, 204));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setIconTextGap(8);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 180, 30));

        btn_delete.setBackground(new java.awt.Color(0, 204, 204));
        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setIconTextGap(8);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 180, 30));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 220, 160));

        m_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        m_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(m_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 280, 950, 160));

        txt_mid.setEditable(false);
        txt_mid.setText("m01");
        txt_mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_midActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 25));
        jPanel1.add(txt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 30));
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));
        jPanel1.add(m_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, 25));

        m_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(m_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 25));
        jPanel1.add(txt_memail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 240, 30));
        jPanel1.add(txt_mcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 240, 25));

        m_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Student", "Others" }));
        jPanel1.add(m_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 240, 25));

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 240, 60));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 970, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel5.setText("Member Id :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel6.setText("Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel7.setText("DOB :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel8.setText("Gender :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel9.setText("Address :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel10.setText("Email-ID :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel11.setText("Contact :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel12.setText("Member Type :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel13.setText("NIC :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 970, 390));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 74, 950, 200));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 990, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_midActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        
        String mid = txt_mid.getText();
        String mname = txt_mname.getText();
        String mnic = txt_nic.getText();
        String dob = ((JTextField)m_dob.getDateEditor().getUiComponent()).getText();
        String gender = m_gender.getSelectedItem().toString();
        String address = txt_address.getText();
        String email = txt_memail.getText();
        String contact = txt_mcontact.getText();
        String type = m_type.getSelectedItem().toString();
        
        try
        {
            String sql = "INSERT INTO `addmember`(`mid`, `mname`, `nic`, `dob`, `gender`, `address`, `email`, `contact`, `type`) VALUES ('"+mid+"', '"+mname+"', '"+mnic+"', '"+dob+"', '"+gender+"', '"+address+"', '"+email+"', '"+contact+"', '"+type+"')";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully Added !! ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        clearField();
        autoId();
        tablelord();
    }//GEN-LAST:event_btn_addActionPerformed

    private void m_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_tableMouseClicked
        
        DefaultTableModel tmodel = (DefaultTableModel)m_table.getModel();
        int selectRowIndex = m_table.getSelectedRow();
        txt_mid.setText(tmodel.getValueAt(selectRowIndex, 0).toString());
        txt_mname.setText(tmodel.getValueAt(selectRowIndex, 1).toString());
        txt_nic.setText(tmodel.getValueAt(selectRowIndex, 2).toString());
        ((JTextField)m_dob.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectRowIndex, 3).toString());
        m_gender.setSelectedItem(tmodel.getValueAt(selectRowIndex, 4).toString());
        txt_address.setText(tmodel.getValueAt(selectRowIndex, 5).toString());
        txt_memail.setText(tmodel.getValueAt(selectRowIndex, 6).toString());
        txt_mcontact.setText(tmodel.getValueAt(selectRowIndex, 7).toString());
        m_type.setSelectedItem(tmodel.getValueAt(selectRowIndex, 8).toString());
        
    }//GEN-LAST:event_m_tableMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        String mid = txt_mid.getText();
        String mname = txt_mname.getText();
        String mnic = txt_nic.getText();
        String dob = ((JTextField)m_dob.getDateEditor().getUiComponent()).getText();
        String gender = m_gender.getSelectedItem().toString();
        String address = txt_address.getText();
        String email = txt_memail.getText();
        String contact = txt_mcontact.getText();
        String type = m_type.getSelectedItem().toString();
        
        try
        {
            String sql = "UPDATE `addmember` SET `mname`='"+mname+"',`nic`='"+mnic+"',`dob`='"+dob+"',`gender`='"+gender+"',`address`='"+address+"',`email`='"+email+"',`contact`='"+contact+"',`type`='"+type+"' WHERE `mid` = '"+mid+"'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Update Successfully !! ");
            tablelord();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        try
        {
            String sql = "DELETE FROM `addmember` WHERE `mid` = '"+txt_mid.getText()+"'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted !! ");
            tablelord();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    
    private void tablelord()
    {
        try
        {
            String sql = "SELECT `mid`, `mname`, `nic`, `dob`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember`";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            m_table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void autoId()
    {
        try
        {
            String sql = "SELECT `mid` FROM `addmember` ORDER BY mid DESC LIMIT 1";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next())
            {
                String rnno = rs.getString("mid");
                int co = rnno.length();
                String txt = rnno.substring(0, 2);
                String num = rnno.substring(2, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                txt_mid.setText(ftxt);
            }
            else
            {
                txt_mid.setText("MI1000");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }
    
    private void clearField()
    {
        txt_mid.setText("");
        txt_mname.setText("");
        txt_nic.setText("");
        //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //dateFormat.format(m_dob.setDate(0));
        ((JTextField)m_dob.getDateEditor().getUiComponent()).setText("");
        m_gender.setSelectedIndex(0);
        txt_address.setText("");
        txt_memail.setText("");
        txt_mcontact.setText("");
        m_type.setSelectedIndex(0);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser m_dob;
    private javax.swing.JComboBox<String> m_gender;
    private javax.swing.JTable m_table;
    private javax.swing.JComboBox<String> m_type;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_mcontact;
    private javax.swing.JTextField txt_memail;
    private javax.swing.JTextField txt_mid;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
