/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gulshan
 */
public class Allmember extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudent
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public Allmember() {
        initComponents();
        con = (Connection) DBCon.getConnection();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_msearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_allmembers = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1020, 540));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 140, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 140, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 153, 255));
        jLabel15.setText("All Members");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Member Name :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, 40));

        txt_msearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_msearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_msearchActionPerformed(evt);
            }
        });
        txt_msearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_msearchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_msearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 130, -1));

        table_allmembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_allmembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_allmembersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_allmembers);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 950, 320));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 970, 50));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 970, 390));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 990, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_allmembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_allmembersMouseClicked
          
    }//GEN-LAST:event_table_allmembersMouseClicked

    private void txt_msearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_msearchActionPerformed
        
    }//GEN-LAST:event_txt_msearchActionPerformed

    private void txt_msearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_msearchKeyReleased
        
        try
        {
            String sql = "SELECT `mid`, `mname`, `nic`, `dob`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember` WHERE mname LIKE '%"+txt_msearch.getText()+"%'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            table_allmembers.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_txt_msearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        txt_msearch.setText("");
        tablelord();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int prcount = table_allmembers.getRowCount();
        if(prcount > 0)
        {
            DefaultTableModel tableModel = (DefaultTableModel)table_allmembers.getModel();
            try
            {
                JasperPrint jasperPrint = null;
                JasperCompileManager.compileReportToFile("C:\\Users\\Gulshan\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\report\\ALLmember.jrxml");
                jasperPrint = JasperFillManager.fillReport("C:\\Users\\Gulshan\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\report\\ALLmember.jasper", null
                , new JRTableModelDataSource(tableModel));
                JasperViewer.viewReport(jasperPrint, false);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Not details to print ! !");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void tablelord()
    {
        try
        {
            String sql = "SELECT `mid`, `mname`, `nic`, `dob`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember`";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            table_allmembers.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_allmembers;
    private javax.swing.JTextField txt_msearch;
    // End of variables declaration//GEN-END:variables
}
