/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import com.mysql.jdbc.Connection;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Gulshan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Connection con = null;
    public Home() {
        initComponents();
        clock();
        con = (Connection) DBCon.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        homeDesktop = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button_allbooks = new javax.swing.JButton();
        button_allmembers = new javax.swing.JButton();
        button_lendhistory = new javax.swing.JButton();
        button_pendinglist = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setPreferredSize(new java.awt.Dimension(1400, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("Book Lend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("Books Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("Add Members");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 240, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("Add Books");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 240, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Central Library NIT Jamshedpur");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 51));
        lblDate.setText("Date");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 100, -1));

        lblTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 51));
        lblTime.setText("Time");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 120, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 40));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 580));

        homeDesktop.setBackground(new java.awt.Color(0, 204, 255));
        homeDesktop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        homeDesktop.setPreferredSize(new java.awt.Dimension(1050, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back10.jpg"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(1050, 500));

        homeDesktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homeDesktopLayout = new javax.swing.GroupLayout(homeDesktop);
        homeDesktop.setLayout(homeDesktopLayout);
        homeDesktopLayout.setHorizontalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeDesktopLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 206, Short.MAX_VALUE))
        );
        homeDesktopLayout.setVerticalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(homeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 1200, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back9.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1470, 620));

        button_allbooks.setBackground(new java.awt.Color(204, 255, 51));
        button_allbooks.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button_allbooks.setText("All Books");
        button_allbooks.setMargin(new java.awt.Insets(2, 40, 0, 40));
        button_allbooks.setMaximumSize(new java.awt.Dimension(140, 25));
        button_allbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_allbooksActionPerformed(evt);
            }
        });
        jPanel1.add(button_allbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        button_allmembers.setBackground(new java.awt.Color(204, 255, 51));
        button_allmembers.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button_allmembers.setText("All Members");
        button_allmembers.setMargin(new java.awt.Insets(2, 40, 0, 40));
        button_allmembers.setMaximumSize(new java.awt.Dimension(140, 25));
        button_allmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_allmembersActionPerformed(evt);
            }
        });
        jPanel1.add(button_allmembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        button_lendhistory.setBackground(new java.awt.Color(204, 255, 51));
        button_lendhistory.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button_lendhistory.setText("Lend History");
        button_lendhistory.setMargin(new java.awt.Insets(2, 40, 0, 40));
        button_lendhistory.setMaximumSize(new java.awt.Dimension(140, 25));
        button_lendhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lendhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(button_lendhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        button_pendinglist.setBackground(new java.awt.Color(204, 255, 51));
        button_pendinglist.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        button_pendinglist.setText("Pending List");
        button_pendinglist.setMargin(new java.awt.Insets(2, 40, 0, 40));
        button_pendinglist.setMaximumSize(new java.awt.Dimension(140, 25));
        button_pendinglist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pendinglistActionPerformed(evt);
            }
        });
        jPanel1.add(button_pendinglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 200, -1));

        jButton9.setBackground(new java.awt.Color(204, 255, 51));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton9.setText("Logout");
        jButton9.setMargin(new java.awt.Insets(2, 50, 0, 50));
        jButton9.setMaximumSize(new java.awt.Dimension(140, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clock()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                try
                {
                    while(true)
                    {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH)+1;
                        int year = cal.get(Calendar.YEAR);
                        
                        int seconds = cal.get(Calendar.SECOND);
                        int minutes = cal.get(Calendar.MINUTE);
                        int hours = cal.get(Calendar.HOUR);
                        
                        lblDate.setText(hours + ":" + minutes + ":" + seconds);
                        lblTime.setText(year + "-" + month + "-" + day);
                        sleep(1000);
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        };
        clock.start();
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        homeDesktop.removeAll();
        AddMember am = new AddMember();
        homeDesktop.add(am).setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        homeDesktop.removeAll();
        AddBooks ab = new AddBooks();
        homeDesktop.add(ab).setVisible(true);
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        homeDesktop.removeAll();
        Borrow brw = new Borrow();
        homeDesktop.add(brw).setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        homeDesktop.removeAll();
        Return rtn = new Return();
        homeDesktop.add(rtn).setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_allbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_allbooksActionPerformed
        
        homeDesktop.removeAll();
        Allbooks abs = new Allbooks();
        homeDesktop.add(abs).setVisible(true);
        
    }//GEN-LAST:event_button_allbooksActionPerformed

    private void button_allmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_allmembersActionPerformed
        
        homeDesktop.removeAll();
        Allmember amb = new Allmember();
        homeDesktop.add(amb).setVisible(true);
        
    }//GEN-LAST:event_button_allmembersActionPerformed

    private void button_lendhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lendhistoryActionPerformed
        
        homeDesktop.removeAll();
        LendHistory lh = new LendHistory();
        homeDesktop.add(lh).setVisible(true);
        
    }//GEN-LAST:event_button_lendhistoryActionPerformed

    private void button_pendinglistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pendinglistActionPerformed
        
        homeDesktop.removeAll();
        PendingList pl = new PendingList();
        homeDesktop.add(pl).setVisible(true);
        
    }//GEN-LAST:event_button_pendinglistActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_allbooks;
    private javax.swing.JButton button_allmembers;
    private javax.swing.JButton button_lendhistory;
    private javax.swing.JButton button_pendinglist;
    private javax.swing.JDesktopPane homeDesktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
