/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gulshan
 */
public class LendHistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudent
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public LendHistory() {
        initComponents();
        con = (Connection) DBCon.getConnection();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_lhsearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_lendhistory = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        from_date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        to_date = new com.toedter.calendar.JDateChooser();
        button_filter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1020, 540));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 140, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 140, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 153, 255));
        jLabel15.setText("Lend History");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Member Id :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, 40));

        txt_lhsearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_lhsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lhsearchActionPerformed(evt);
            }
        });
        txt_lhsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lhsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_lhsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 130, -1));

        table_lendhistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_lendhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_lendhistoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_lendhistory);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 950, 320));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("From :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        from_date.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(from_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 120, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("To :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        to_date.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(to_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 120, 30));

        button_filter.setBackground(new java.awt.Color(0, 153, 153));
        button_filter.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        button_filter.setText("Filter");
        button_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_filterActionPerformed(evt);
            }
        });
        jPanel1.add(button_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 90, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 970, 50));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 970, 390));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 990, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_lendhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_lendhistoryMouseClicked
          
    }//GEN-LAST:event_table_lendhistoryMouseClicked

    private void txt_lhsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lhsearchActionPerformed
        
    }//GEN-LAST:event_txt_lhsearchActionPerformed

    private void txt_lhsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lhsearchKeyReleased
        
        try
        {
            String sql = "SELECT `record_no`, `mid`, `bid`, `issue_date`, `return_date`, `mark` FROM `booklend` WHERE mid LIKE '%"+txt_lhsearch.getText()+"%'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            table_lendhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_txt_lhsearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        txt_lhsearch.setText("");
        tablelord();
        ((JTextField)from_date.getDateEditor().getUiComponent()).setText("");
        ((JTextField)to_date.getDateEditor().getUiComponent()).setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_filterActionPerformed
        
        lendFilter();
        
    }//GEN-LAST:event_button_filterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int prcount = table_lendhistory.getRowCount();
        if(prcount > 0)
        {
            DefaultTableModel tableModel = (DefaultTableModel)table_lendhistory.getModel();
            try
            {
                JasperPrint jasperPrint = null;
                JasperCompileManager.compileReportToFile("C:\\Users\\Gulshan\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\report\\LendHistory.jrxml");
                jasperPrint = JasperFillManager.fillReport("C:\\Users\\Gulshan\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\report\\LendHistory.jasper", null
                , new JRTableModelDataSource(tableModel));
                JasperViewer.viewReport(jasperPrint, false);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Not details to print ! !");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lendFilter()
    {
        String FDate = ((JTextField)from_date.getDateEditor().getUiComponent()).getText().toString();
        String TDate = ((JTextField)to_date.getDateEditor().getUiComponent()).getText().toString();
        if(FDate.length()>0 && TDate.isEmpty())
        {
            try
            {
                String sql = "SELECT `record_no`, `mid`, `bid`, `issue_date`, `return_date`, `mark` FROM `booklend` WHERE issue_date = '"+FDate+"' AND mid LIKE '%"+txt_lhsearch.getText()+"%'";
                ps = (PreparedStatement) con.prepareStatement(sql);
                rs = ps.executeQuery();
                table_lendhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "First Date");
            }
        }
        
        else if(FDate.length()>0 && TDate.length()>0)
        {
            try
            {
                String sql = "SELECT `record_no`, `mid`, `bid`, `issue_date`, `return_date`, `mark` FROM `booklend` WHERE mid LIKE '%"+txt_lhsearch.getText()+"%' AND issue_date between '"+FDate+"' AND '"+TDate+"'";
                ps = (PreparedStatement) con.prepareStatement(sql);
                rs = ps.executeQuery();
                table_lendhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Select Date to filter data !");
        }
    }
    
    private void tablelord()
    {
        try
        {
            String sql = "SELECT `record_no`, `mid`, `bid`, `issue_date`, `return_date`, `mark` FROM `booklend`";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            table_lendhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_filter;
    private com.toedter.calendar.JDateChooser from_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_lendhistory;
    private com.toedter.calendar.JDateChooser to_date;
    private javax.swing.JTextField txt_lhsearch;
    // End of variables declaration//GEN-END:variables
}
