/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gulshan
 */
public class Return extends javax.swing.JInternalFrame {

    /**
     * Creates new form Return
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    public Return() {
        initComponents();
        con = (Connection) DBCon.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_bid = new javax.swing.JTextField();
        txt_mid = new javax.swing.JTextField();
        txt_ldays = new javax.swing.JTextField();
        txt_fine = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1010, 540));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText(" Return");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 880, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel6.setText("Book Id :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel7.setText("Member Id :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel8.setText("Late Days :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel9.setText("Fine :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txt_bid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_bid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bidKeyReleased(evt);
            }
        });
        jPanel1.add(txt_bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        txt_mid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, -1));

        txt_ldays.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_ldays, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 160, -1));

        txt_fine.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fineActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 160, -1));

        txt_bill.setColumns(20);
        txt_bill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_bill.setRows(5);
        jScrollPane1.setViewportView(txt_bill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 260, 290));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 413, 340, 60));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 300, 60));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 330));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 300, 330));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 900, 480));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fineActionPerformed

    private void txt_bidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bidKeyReleased
        
        try
        {
            String sql = "SELECT `mid`, `return_date` FROM `bookLend` WHERE bid='"+txt_bid.getText()+"' AND mark = '0'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next())
            {
                txt_mid.setText(rs.getString("mid"));
                String r_date = rs.getString("return_date");
                LocalDate today = LocalDate.now();
                LocalDate rday = LocalDate.parse(r_date);
                
                Long day_gap = ChronoUnit.DAYS.between(rday, today);
                if(day_gap > 0)
                {
                    txt_ldays.setText(day_gap.toString());
                
                    long fine = 10*day_gap;
                    txt_fine.setText(String.valueOf(fine));
                }
                else
                {
                    txt_ldays.setText("0");
                    txt_fine.setText("0");
                }
                
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_txt_bidKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String bid = txt_bid.getText();
        String mid = txt_mid.getText();
        String ldate = txt_ldays.getText();
        String fine = txt_fine.getText();
        
        try
        {
            String sql = "INSERT INTO `bookreturn`(`bid`, `mid`, `late_days`, `fine`) VALUES ('"+bid+"', '"+mid+"', '"+ldate+"', '"+fine+"')";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ps.execute();
            update();
            bill();
            markReturn();
            JOptionPane.showMessageDialog(rootPane, "Successfully Added !! ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            txt_bill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bill()
    {
        txt_bill.setText("==============" + "\n"
                         + "Library Name" + "\n"
                         + "No of Date\t" + txt_ldays.getText() + "\n"
                         + "Amount\t" + txt_fine.getText() + "\n"
                         + "==============");
    }
    
    private void update()
    {
        try
        {
            String sql = "UPDATE ``addbook` SET mark = '0' WHERE bid = '"+txt_bid.getText()+"'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(rootPane, "Successfully Updated !! ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void markReturn()
    {
        try
        {
            String sql = "UPDATE ``booklend` SET mark = '1' WHERE bid = '"+txt_bid.getText()+"'";
            ps = (PreparedStatement) con.prepareStatement(sql);
            rs = ps.executeQuery();
            //JOptionPane.showMessageDialog(rootPane, "Successfully Updated !! ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_bid;
    private javax.swing.JTextArea txt_bill;
    private javax.swing.JTextField txt_fine;
    private javax.swing.JTextField txt_ldays;
    private javax.swing.JTextField txt_mid;
    // End of variables declaration//GEN-END:variables
}
